Vagrant.configure("2") do |config|
  config.vm.box = "generic/fedora32"
  # config.ssh.username = 'root'
  # config.ssh.password = 'vagrant'
  # config.ssh.insert_key = 'true'
  config.vm.network "forwarded_port", guest: 1317, host: 1317
  config.vm.network "forwarded_port", guest: 7545, host: 7545
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "forwarded_port", guest: 26656, host: 26656
  config.vm.network "forwarded_port", guest: 26657, host: 26657

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end

  config.vm.provision "shell", inline: <<-SHELL
    dnf update
    dnf -y install podman criu
    echo "cd /home/vagrant/go/src/github.com/Sifchain/sifnode" >> /home/vagrant/.bashrc
  SHELL

  config.vm.synced_folder "..", "/home/vagrant/go/src/github.com/Sifchain/sifnode", type: "rsync", rsync__exclude: [".vagrant/", ".git/", "**/node_modules/"]
end